/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Functions.AnalyzeSummary;
import classes.HashTable;
import classes.Resumen;
import java.util.LinkedHashSet;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dsre1
 */
public class AutorForm extends javax.swing.JFrame {

    AnalyzeSummary analyzeSummary;
    HashTable hashTable;

    /**
     * Creates new form AutorForm
     */
    public AutorForm(HashTable hashTable, String asd) {
        initComponents();

        this.analyzeSummary = new AnalyzeSummary();
        this.hashTable = hashTable;

        this.setModel();
    }

    private boolean buscar(String[] palabras, String palabra) {
        for (int i = 0; i < palabras.length; i++) {
            if (palabras[i].equals(palabra)) {
                return true;
            }
        }
        return false;
    }

    private String[] agregar(String[] palabras, String palabra) {
        String[] temp = new String[palabras.length + 1];
        
        for(int i = 0; i < palabras.length; i++) {
            temp[i] = palabras[i];
        }
        
        temp[palabras.length] = palabra;
        
        return temp;
    }

    private Resumen[] agregar(Resumen[] resumenes, Resumen resumen) {
        Resumen[] temp = new Resumen[resumenes.length + 1];
        
        for(int i = 0; i < resumenes.length; i++) {
            temp[i] = resumenes[i];
        }
        
        temp[resumenes.length] = resumen;
        
        return temp;
        
    }

    

    public void setModel() {
        Resumen[] resumenes = this.hashTable.getOriginal();
        String[] autores = new String[0];

        for (int i = 0; i < resumenes.length; i++) {
            String[] autores_original = resumenes[i].getAutores();
            for (int j = 0; j < autores_original.length; j++) {
                String autor = autores_original[j];
                if(!this.buscar(autores, autor)) {
                    autores = this.agregar(autores, autor);
                }
            }
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel(autores);

        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Articulos por Autor");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String evaluate = jList1.getSelectedValue();

        Resumen[] resumenes = new Resumen[0];
        
        for (int i = 0; i < this.hashTable.getOriginal().length; i++) {
            Resumen resumen_original = this.hashTable.getOriginal()[i];
            String[] autores_original = this.hashTable.getOriginal()[i].getAutores();
            for (int j = 0; j < autores_original.length; j++) {
                if (this.buscar(autores_original, evaluate)) {
                    resumenes = this.agregar(resumenes, resumen_original);
                    break;
                }
            }
        }
        
        System.out.println(resumenes.length);
        
        for(int i = 0; i < resumenes.length; i++) {
            System.out.println(resumenes[i].getTitulo());
        }

        Busqueda busqueda = new Busqueda(this.hashTable, resumenes, "a");

        busqueda.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
